ticket = int(input('Введите шестизначный номер билета: '))
firstthree_summ = 0
lastthree_summ = 0
counter = 0
while counter != 3:
    last_num = ticket % 10
    lastthree_summ += last_num
    ticket //= 10
    counter += 1
while ticket != 0:
    last_num = ticket % 10
    firstthree_summ += last_num
    ticket //= 10
    counter += 1
print('Сумма первых трех цифр =', firstthree_summ)
print('Сумма последних трёх цифр =', lastthree_summ)